events {
    worker_connections 1024;
}

http {
    upstream authorization_upstream {
        server authorization-service:8080;
    }

    upstream employee_upstream {
        server employee-service:8081;
    }

    server {
        listen 80;

        location /peoplesuite/apis/token {
            proxy_pass http://authorization_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /peoplesuite/apis/employees {
            proxy_pass http://employee_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            client_max_body_size 10m;
        }

        location /health {
            return 200 "nginx ok\n";
            add_header Content-Type text/plain;
        }
    }
}
